import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ModalProvider } from "./context/ModalContext";
import EnrollModal from "@/components/EnrollModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Parallel.edu - Tech Bootcamps with Job Guarantee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <Navbar />
          {children}
          <EnrollModal /> {/* Global popup available everywhere */}
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
