import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ModalProvider } from "./context/ModalContext";
import EnrollModal from "@/components/EnrollModal";
import ScrollToTop from "./ScrollToTop";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Parallel.edu - Tech Bootcamps with Job Guarantee",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" }
    ],
    shortcut: "/favicon.svg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <ScrollToTop />
          <Navbar />
          {children}
          <ToastContainer position="bottom-right" draggable />
          <EnrollModal />
          <Footer />
        </ModalProvider>
      </body>
      */}
      <body style={{ margin: 0, fontFamily: 'sans-serif' }}>
        <div style={{ 
          display: 'flex', 
          justifyContent: 'center', 
          alignItems: 'center', 
          height: '100vh', 
          width: '100vw',
          backgroundColor: '#111',
          backgroundImage: 'linear-gradient(156.63deg, #201da7 8.68%, #30e29d 84.91%)',
          position: 'fixed',
          top: 0,
          left: 0,
          zIndex: 9999
        }}>
          <div style={{ 
            padding: '50px 40px', 
            backgroundColor: '#fff', 
            borderRadius: '16px', 
            boxShadow: '0 10px 40px rgba(0,0,0,0.2)', 
            textAlign: 'center',
            maxWidth: '450px',
            width: '90%'
          }}>
            {/* <h2 style={{ marginTop: 0, marginBottom: '16px', fontSize: '28px', color: '#111', fontWeight: '800', letterSpacing: '-0.5px' }}>
              We've Moved!
            </h2>
            <p style={{ marginBottom: '32px', color: '#555', lineHeight: '1.6', fontSize: '16px' }}>
        Please click below to continue to our platform.
            </p> */}
            <a 
              href="https://tech.paralleledu.com" 
              style={{ 
                display: 'inline-block', 
                padding: '16px 32px', 
                background: '#111', 
                color: '#fff', 
                textDecoration: 'none', 
                borderRadius: '8px', 
                fontWeight: 'bold',
                fontSize: '18px',
                boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)',
              }}
            >
             Click here to continue
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
